// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWOYMqj9nXeZ5jnTP6Kwd65ZqX2LmSjY',
    appId: '1:830753725892:web:0181331f984a1ec7529891',
    messagingSenderId: '830753725892',
    projectId: 'ecommerceapp-tstore',
    authDomain: 'ecommerceapp-tstore.firebaseapp.com',
    storageBucket: 'ecommerceapp-tstore.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVzWGchsBghvvfQ7MUNNi72vDJzlBZ3Fg',
    appId: '1:830753725892:android:cd4fe820ebe6143f529891',
    messagingSenderId: '830753725892',
    projectId: 'ecommerceapp-tstore',
    storageBucket: 'ecommerceapp-tstore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5YlRkaALY9I-VOWs_dVPG1xYAElFK-3k',
    appId: '1:830753725892:ios:acad93644f419126529891',
    messagingSenderId: '830753725892',
    projectId: 'ecommerceapp-tstore',
    storageBucket: 'ecommerceapp-tstore.appspot.com',
    androidClientId: '830753725892-pd9l5nbvp5jd7ermpmfh5v9hp61nveur.apps.googleusercontent.com',
    iosClientId: '830753725892-d5fngbib5gj1a600hmtb3pstui335kuk.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
